# Generated by Django 3.2.5 on 2021-08-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadimage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='job_data',
            new_name='job_date',
        ),
    ]
